/**
 * This file was auto-generated by swagger-to-ts.
 * Do not make direct changes to the file.
 */

export interface definitions {
  /**
   * company metadata
   */
  CompanyDO: {
    ctime?: number;
    id?: number;
    key?: string;
    mtime?: number;
    name?: string;
    remark?: string;
  };
  /**
   * csv job metadata
   */
  CsvJobDO: {
    creator?: string;
    ctime?: number;
    dagId?: string;
    dataInsertMode?: number;
    enableAutoTableEvolution?: boolean;
    id?: number;
    jobKey?: string;
    lastUploadId?: number;
    mtime?: number;
    outDatabaseName?: string;
    outTableName?: string;
    remark?: string;
  };
  /**
   * Database metadata
   */
  DatabaseDO: {
    ctime?: number;
    id?: number;
    mtime?: number;
    name?: string;
    remark?: string;
  };
  EmptyResponse: { message?: string };
  /**
   * global error message model
   */
  ErrorResponse: {
    error?: string;
    message?: string;
    /**
     * request path
     */
    path?: string;
    status?: number;
    timestamp?: string;
    trace?: string;
    /**
     * violation of each field
     */
    violations?: definitions["Violation"][];
  };
  /**
   * Job Info
   */
  JobInfoDTO: {
    /**
     * Ingestion Mode
     */
    dataInsertMode: "0" | "1";
    /**
     * Enable Auto Evolution
     */
    enableAutoTableEvolution: boolean;
    fileOriginalName?: string;
    fileSize?: number;
    id: number;
    jobKey?: string;
    jobLog?: string;
    /**
     * 0: created, 1: uploading, 2: uploading failed, 3: ingesting, 4: ingestion failed, 5: successful
     */
    jobStatus?: "0" | "1" | "2" | "3" | "4" | "5";
    lastUploadStartTime?: number;
    /**
     * Database (schema)
     */
    outDatabaseName: string;
    /**
     * Table
     */
    outTableName: string;
    /**
     * PIC list
     */
    pics: string[];
  };
  "PageResponse«JobInfoDTO»": {
    data?: definitions["JobInfoDTO"][];
    total?: number;
  };
  /**
   * TeamFunction metadata
   */
  TeamFunctionDO: {
    ctime?: number;
    id?: number;
    key?: string;
    mtime?: number;
    name?: string;
    remark?: string;
  };
  /**
   * TeamScope metadata
   */
  TeamScopeDO: {
    ctime?: number;
    id?: number;
    key?: string;
    mtime?: number;
    name?: string;
    remark?: string;
  };
  /**
   * Upload Token
   */
  UploadTokenDTO: { token?: string };
  /**
   * User Info
   */
  UserInfoDTO: {
    email?: string;
    id?: string;
    isAdmin?: boolean;
    name?: string;
  };
  Violation: { fieldName?: string; message?: string };
}
